# Simple makefile for Viscometric-ViscoPlastic-Flow (ver. 1.0)
gnu:
	gfortran -o VVPF_v10 param.f90 shear.f90 viscous.f90 update.f90 motion.f90 write2f.f90 main.f90
intel:
	ifort -o VVPF_v10 param.f90 shear.f90 viscous.f90 update.f90 motion.f90 write2f.f90 main.f90
